version: "3"
# services define types of containers
# docker-compose automatically networks defined containers
services:
    postgres:
        image: "postgres:latest"
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: "redis:latest"
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
        # command: ["npm", "run", "test"]
        #
